window.GAME_DATA['Персонажи игр'] = [
    {"name":"2B (NieR: Automata)","image":""},
    {"name":"9S (NieR: Automata)","image":""},
    {"name":"Авелин (Dragon Age)","image":""},
    {"name":"Агент 47 (Hitman)","image":""},
    {"name":"Адрия (Diablo)","image":""},
    {"name":"Айзек Кларк (Dead Space)","image":""},
    {"name":"Айрис Гейнсборо (Final Fantasy VII)","image":""},
    {"name":"Алан Уэйк (Alan Wake)","image":""},
    {"name":"Алдуин (Skyrim)","image":""},
    {"name":"Алекс (Minecraft)","image":""},
    {"name":"Аликс Вэнс (Half-Life)","image":""},
    {"name":"Алистер (Dragon Age)","image":""},
    {"name":"Алистер (Dragon Age)","image":""},
    {"name":"Алхимик (Torchlight)","image":""},
    {"name":"Альтаир (Assassins Creed)","image":""},
    {"name":"Андерс (Dragon Age)","image":""},
    {"name":"Андрэ (Dark Souls)","image":""},
    {"name":"Аргонианин (Skyrim)","image":""},
    {"name":"Арториас (Dark Souls)","image":""},
    {"name":"Артур Морган (RDR 2)","image":""},
    {"name":"Астрид (Skyrim)","image":""},
    {"name":"Атрей (God of War)","image":""},
    {"name":"Баал (Diablo)","image":""},
    {"name":"Байонетта (Bayonetta)","image":""},
    {"name":"Беатрис (Dark Souls)","image":""},
    {"name":"Биг Босс (Metal Gear Solid)","image":""},
    {"name":"Блэкуолл (Dragon Age)","image":""},
    {"name":"Боузер (Super Mario)","image":""},
    {"name":"Бретон (Skyrim)","image":""},
    {"name":"Бриньольф (Skyrim)","image":""},
    {"name":"Бэтмен (Arkham Series)","image":""},
    {"name":"Варрик (Dragon Age)","image":""},
    {"name":"Вергилий (Devil May Cry)","image":""},
    {"name":"Вивьен (Dragon Age)","image":""},
    {"name":"Виктор Вэнс (GTA: VCS)","image":""},
    {"name":"Высокий эльф (Skyrim)","image":""},
    {"name":"Гаррус (Mass Effect)","image":""},
    {"name":"Гвин (Dark Souls)","image":""},
    {"name":"Гвиневер (Dark Souls)","image":""},
    {"name":"Генерал Туллий (Skyrim)","image":""},
    {"name":"Геральт (The Witcher)","image":""},
    {"name":"Гладос (Portal)","image":""},
    {"name":"Голланд ван дер Линде (RDR 2)","image":""},
    {"name":"Гордон Фримен (Half-Life)","image":""},
    {"name":"Гох (Dark Souls)","image":""},
    {"name":"Григгс (Dark Souls)","image":""},
    {"name":"Данте (Devil May Cry)","image":""},
    {"name":"Дарк Соулс (Избранный мертвец)","image":""},
    {"name":"Декард Каин (Diablo)","image":""},
    {"name":"Дельфина (Skyrim)","image":""},
    {"name":"Детектив Пикачу (Pokemon)","image":""},
    {"name":"Джеймс Каш (Manhunt)","image":""},
    {"name":"Джесси Фейден (Control)","image":""},
    {"name":"Джимми Хопкинс (Bully)","image":""},
    {"name":"Джокер (Arkham Series)","image":""},
    {"name":"Джон Марстон (RDR 1/2)","image":""},
    {"name":"Джони Кейдж (Mortal Kombat)","image":""},
    {"name":"Джонни Клебиц (GTA IV: TLAD)","image":""},
    {"name":"Джоэл (The Last of Us)","image":""},
    {"name":"Диабло (Diablo)","image":""},
    {"name":"Доминик Сантьяго (Gears of War)","image":""},
    {"name":"Дориан (Dragon Age)","image":""},
    {"name":"Дракон Края (Minecraft)","image":""},
    {"name":"Думгай (DOOM)","image":""},
    {"name":"Железный Бык (Dragon Age)","image":""},
    {"name":"Зевран (Dragon Age)","image":""},
    {"name":"Зельда (The Legend of Zelda)","image":""},
    {"name":"Изабелла (Dragon Age)","image":""},
    {"name":"Имперский (Skyrim)","image":""},
    {"name":"Инарий (Diablo IV)","image":""},
    {"name":"Йеннифэр (The Witcher)","image":""},
    {"name":"Каджит (Skyrim)","image":""},
    {"name":"Каламит (Dark Souls)","image":""},
    {"name":"Карлия (Skyrim)","image":""},
    {"name":"Кассандра (Assassins Creed Odyssey)","image":""},
    {"name":"Кассандра (Dragon Age)","image":""},
    {"name":"Квилана (Dark Souls)","image":""},
    {"name":"Квилег (Dark Souls)","image":""},
    {"name":"Кен (Street Fighter)","image":""},
    {"name":"Киаран (Dark Souls)","image":""},
    {"name":"Киттана (Mortal Kombat)","image":""},
    {"name":"Клауд Страйф (Final Fantasy VII)","image":""},
    {"name":"Клод (GTA III)","image":""},
    {"name":"Коннор (Assassins Creed III)","image":""},
    {"name":"Кортана (Halo)","image":""},
    {"name":"Коул (Dragon Age)","image":""},
    {"name":"Коул Фелпс (L.A. Noire)","image":""},
    {"name":"Кратос (God of War)","image":""},
    {"name":"Крипер (Minecraft)","image":""},
    {"name":"Ксантос (Dark Souls)","image":""},
    {"name":"Лаврентий (Dark Souls)","image":""},
    {"name":"Лара Крофт (Tomb Raider)","image":""},
    {"name":"Лелиана (Dragon Age)","image":""},
    {"name":"Лелиана (Mass Effect)","image":""},
    {"name":"Лерой (Dark Souls)","image":""},
    {"name":"Лесной эльф (Skyrim)","image":""},
    {"name":"Лиара (Mass Effect)","image":""},
    {"name":"Лидия (Skyrim)","image":""},
    {"name":"Лилит (Diablo IV)","image":""},
    {"name":"Линк (The Legend of Zelda)","image":""},
    {"name":"Лия (Diablo III)","image":""},
    {"name":"Логан (Dark Souls)","image":""},
    {"name":"Логэйн (Dragon Age)","image":""},
    {"name":"Лорт (Diablo)","image":""},
    {"name":"Луиджи (Super Mario)","image":""},
    {"name":"Луис Лопес (GTA IV: TBoGT)","image":""},
    {"name":"Лю Кан (Mortal Kombat)","image":""},
    {"name":"Лютик (The Witcher)","image":""},
    {"name":"Майкл Де Санта (GTA V)","image":""},
    {"name":"Майлз Моралес (Spider-Man)","image":""},
    {"name":"Макс Пейн (Max Payne)","image":""},
    {"name":"Малтаэль (Diablo III)","image":""},
    {"name":"Манус (Dark Souls)","image":""},
    {"name":"Марио (Super Mario)","image":""},
    {"name":"Мариус (Diablo II)","image":""},
    {"name":"Маркус Фенли (Gears of War)","image":""},
    {"name":"Мастер Чиф (Halo)","image":""},
    {"name":"Мерриль (Dragon Age)","image":""},
    {"name":"Мерсер Фрей (Skyrim)","image":""},
    {"name":"Мефисто (Diablo)","image":""},
    {"name":"Морриган (Dragon Age)","image":""},
    {"name":"Морриган (Dragon Age)","image":""},
    {"name":"Наклз (Sonic)","image":""},
    {"name":"Нейтан Дрейк (Uncharted)","image":""},
    {"name":"Неро (Devil May Cry)","image":""},
    {"name":"Нико Беллич (GTA IV)","image":""},
    {"name":"Норд (Skyrim)","image":""},
    {"name":"Орк (Skyrim)","image":""},
    {"name":"Орнштейн (Dark Souls)","image":""},
    {"name":"Оскар из Асторы (Dark Souls)","image":""},
    {"name":"Папирус (Undertale)","image":""},
    {"name":"Партурнакс (Skyrim)","image":""},
    {"name":"Патчес (Dark Souls)","image":""},
    {"name":"Пикачу (Pokemon)","image":""},
    {"name":"Питер Паркер (Spider-Man PS4)","image":""},
    {"name":"Пич (Super Mario)","image":""},
    {"name":"Прекрасная Госпожа (Dark Souls)","image":""},
    {"name":"Разрушитель (Torchlight)","image":""},
    {"name":"Райден (Metal Gear)","image":""},
    {"name":"Райдэн (Mortal Kombat)","image":""},
    {"name":"Редгард (Skyrim)","image":""},
    {"name":"Рикард (Dark Souls)","image":""},
    {"name":"Рю (Street Fighter)","image":""},
    {"name":"Саб-Зиро (Mortal Kombat)","image":""},
    {"name":"Санс (Undertale)","image":""},
    {"name":"Себастьян (Dragon Age)","image":""},
    {"name":"Серана (Skyrim)","image":""},
    {"name":"Серафина (Dragon Age)","image":""},
    {"name":"Сефирот (Final Fantasy VII)","image":""},
    {"name":"Си-Джей (GTA: San Andreas)","image":""},
    {"name":"Сигланда (Dark Souls)","image":""},
    {"name":"Сигмайер из Катарины (Dark Souls)","image":""},
    {"name":"Сиф (Dark Souls)","image":""},
    {"name":"Скорпион (Mortal Kombat)","image":""},
    {"name":"Следопыт (Torchlight)","image":""},
    {"name":"Смоуг (Dark Souls)","image":""},
    {"name":"Солас (Dragon Age)","image":""},
    {"name":"Солас (Dragon Age)","image":""},
    {"name":"Солер из Асторы (Dark Souls)","image":""},
    {"name":"Солид Снейк (Metal Gear Solid)","image":""},
    {"name":"Соник (Sonic the Hedgehog)","image":""},
    {"name":"Соня Блейд (Mortal Kombat)","image":""},
    {"name":"Стив (Minecraft)","image":""},
    {"name":"Сэм Фишер (Splinter Cell)","image":""},
    {"name":"Тали (Mass Effect)","image":""},
    {"name":"Таркус (Dark Souls)","image":""},
    {"name":"Тейлз (Sonic)","image":""},
    {"name":"Темный эльф (Skyrim)","image":""},
    {"name":"Тираэль (Diablo)","image":""},
    {"name":"Тифа Локхарт (Final Fantasy VII)","image":""},
    {"name":"Томми Версетти (GTA: Vice City)","image":""},
    {"name":"Тони Сиприани (GTA: LCS)","image":""},
    {"name":"Торчлайт (Torchlight)","image":""},
    {"name":"Тревор Филиппс (GTA V)","image":""},
    {"name":"Трисс (The Witcher)","image":""},
    {"name":"Уитли (Portal 2)","image":""},
    {"name":"Ульфрик Буревестник (Skyrim)","image":""},
    {"name":"Фенрис (Dragon Age)","image":""},
    {"name":"Франклин Клинтон (GTA V)","image":""},
    {"name":"Фриск (Undertale)","image":""},
    {"name":"Цири (The Witcher)","image":""},
    {"name":"Цицерон (Skyrim)","image":""},
    {"name":"Челл (Portal)","image":""},
    {"name":"Чунь Ли (Street Fighter)","image":""},
    {"name":"Шао Кан (Mortal Kombat)","image":""},
    {"name":"Шейла (Dragon Age)","image":""},
    {"name":"Шепард (Mass Effect)","image":""},
    {"name":"Эбби (The Last of Us)","image":""},
    {"name":"Эдвард Кенуэй (Assassins Creed IV)","image":""},
    {"name":"Эйвор (Assassins Creed Valhalla)","image":""},
    {"name":"Элли (The Last of Us)","image":""},
    {"name":"Энги (Dark Souls)","image":""},
    {"name":"Эсберн (Skyrim)","image":""},
    {"name":"Эцио Аудиторе (Assassins Creed)","image":""},
    {"name":"G-Man (Half-Life)","image":""}
];