window.GAME_DATA['Герои и злодеи'] = [
    {"name":"Аквамен","image":"images/heroes_and_villains/ALV-UjVxjSj-chu0tIVCJlsHifYSo7JM5pTimqXKImGUbfTZn29pyFmz"},
    {"name":"Алая Ведьма","image":"images/heroes_and_villains/orig"},
    {"name":"Альтрон","image":"images/heroes_and_villains/ultron.jpg"},
    {"name":"Апокалипсис","image":"images/heroes_and_villains/latest"},
    {"name":"Арес","image":"https://upload.wikimedia.org/wikipedia/ru/thumb/d/d3/AresDC.webp/330px-AresDC.webp.png"},
    {"name":"Блэйд","image":"images/heroes_and_villains/blejd.jpg"},
    {"name":"Бэйн","image":"images/heroes_and_villains/1714456812197296348.jpg"},
    {"name":"Бэтгерл","image":"https://upload.wikimedia.org/wikipedia/ru/d/dc/Barbara_Gordon_Batgirl.png"},
    {"name":"Бэтмен","image":"images/heroes_and_villains/Where-to-start-read-Batman-comics.jpg"},
    {"name":"Веном","image":"images/heroes_and_villains/what-are-some-good-venom-comics-i-can-look-for-v0-chuh86okyxrb1.jpg"},
    {"name":"Вижн","image":"images/heroes_and_villains/444"},
    {"name":"Галактус","image":"images/heroes_and_villains/comics-am-i-the-only-that-doesnt-really-view-galactus-as-v0-nvazvdbt0kqd1.jpeg"},
    {"name":"Гамора","image":"images/heroes_and_villains/s1200.jpg"},
    {"name":"Грут","image":"images/heroes_and_villains/groot.jpg"},
    {"name":"Дарксайд","image":"images/heroes_and_villains/89334-65056-darkseid.png"},
    {"name":"Двуликий","image":"images/heroes_and_villains/1687713266159545059.jpg"},
    {"name":"Детстроук","image":"images/heroes_and_villains/deathstroke_3.jpg"},
    {"name":"Джокер","image":"images/heroes_and_villains/cover256x256-05a95854dd2d47399e72bac97ec706af.jpg"},
    {"name":"Доктор Дум","image":"images/heroes_and_villains/i-want-to-read-comics-about-dr-doom-any-recommendations-v0-gquazsm0k0xb1.jpg"},
    {"name":"Доктор Осьминог","image":"images/heroes_and_villains/day-11-best-story-of-doctor-octopus-v0-u4dvcbajfctd1.jpg"},
    {"name":"Доктор Стрэндж","image":"images/heroes_and_villains/78.jpg"},
    {"name":"Дормамму","image":"https://upload.wikimedia.org/wikipedia/ru/6/67/Defenders_Vol_3_3_Textless.jpg"},
    {"name":"Дракс","image":"images/heroes_and_villains/22dd9fcaacf111ee90d93a4a133f64ae:upscaled"},
    {"name":"Думсдэй","image":"images/heroes_and_villains/76295aabf941e38a85f7e1b97e722c80.jpg"},
    {"name":"Дэдпул","image":"images/heroes_and_villains/efjf2zojz1qb1.jpg"},
    {"name":"Дэдшот","image":"images/heroes_and_villains/4e1c2854eeb7400fb212b71a2f6c6d47.jpg"},
    {"name":"Железный человек","image":"images/heroes_and_villains/orig"},
    {"name":"Женщина-кошка","image":"images/heroes_and_villains/a61c07502a2211eea572522415d39c57:upscaled"},
    {"name":"Женщина-невидимка","image":"images/heroes_and_villains/1597346403_nevidimaya-ledi-invisible-woman.jpg"},
    {"name":"Загадочник","image":"images/heroes_and_villains/960"},
    {"name":"Звездный Лорд","image":"https://upload.wikimedia.org/wikipedia/ru/7/77/Star-Lord.png"},
    {"name":"Зеленый Гоблин","image":"images/heroes_and_villains/250"},
    {"name":"Зеленый Фонарь","image":"https://geekach.com.ua/content/uploads/images/62%281%29.jpg"},
    {"name":"Зимний Солдат","image":"images/heroes_and_villains/9e5a4de4a0f35f86a8d8d58cbf9fe0fe.jpg"},
    {"name":"Капитан Америка","image":"images/heroes_and_villains/600"},
    {"name":"Капитан Марвел","image":"images/heroes_and_villains/20180718224143c4a20f21f9.jpg"},
    {"name":"Каратель","image":"images/heroes_and_villains/main.jpg"},
    {"name":"Киборг","image":"https://upload.wikimedia.org/wikipedia/ru/5/58/Cyborg_%28Victor_Stone%29.jpg"},
    {"name":"Кингпин","image":"https://static.wikia.nocookie.net/marvel-dc/images/2/20/250px-Kingpinm.png/revision/latest?cb=20180708145157"},
    {"name":"Красный Колпак","image":"images/heroes_and_villains/be2a6027c8306fa1c82cc689a74d97a5.jpg"},
    {"name":"Красный Череп","image":"images/heroes_and_villains/3025e08abff54ae3b34b8195c320aac1_orig.jpg"},
    {"name":"Лекс Лютор","image":"images/heroes_and_villains/what-is-the-most-evil-disturbing-and-unsettling-thing-lex-v0-l53mwpewfjdd1.jpg"},
    {"name":"Локи","image":"images/heroes_and_villains/1596380418_loki.jpg"},
    {"name":"Магнето","image":"https://static.tvtropes.org/pmwiki/pub/images/fdd88dfe_16c5_4d80_87ff_d49e8cfc344c.jpeg"},
    {"name":"Марсианский Охотник","image":"images/heroes_and_villains/1455884406_marsianskiy-ohotnik-poyavlyaetsya-v-staticheskiy-shok.jpg"},
    {"name":"Мистер Фантастик","image":"images/heroes_and_villains/1597214822_mister-fantastik-mister-fantastic-rid-richards.jpg"},
    {"name":"Мистерио","image":"images/heroes_and_villains/images"},
    {"name":"Мистик","image":"https://static.wikia.nocookie.net/xmenmovies/images/0/00/Mystique_04.jpg"},
    {"name":"Морбиус","image":"images/heroes_and_villains/morbius-marvel-2.jpg"},
    {"name":"Найтвинг","image":"https://static.wikia.nocookie.net/gotem/images/5/53/250px-Nightwing_001.jpg/revision/latest?cb=20140629213315&path-prefix=ru"},
    {"name":"Орлица","image":"images/heroes_and_villains/1474844933_orlica-v-multseriale-liga-spravedlivosti.jpg"},
    {"name":"Песочный человек","image":"images/heroes_and_villains/z6j516s5drgd1.png"},
    {"name":"Пингвин","image":"images/heroes_and_villains/dc-comics-batman-gotham-doma------.jpg"},
    {"name":"Призрачный гонщик","image":"images/heroes_and_villains/images"},
    {"name":"Профессор Икс","image":"https://upload.wikimedia.org/wikipedia/ru/e/e9/Professor_x.jpg"},
    {"name":"Пугало","image":"images/heroes_and_villains/1078363-scarecrow_1_super.jpg"},
    {"name":"Ра’с аль Гул","image":"images/heroes_and_villains/1595936260_ras-al-gul.jpg"},
    {"name":"Ракета","image":"images/heroes_and_villains/1545992441_raketa-rocket-raccoon.gif"},
    {"name":"Рейвен","image":"https://upload.wikimedia.org/wikipedia/ru/0/0e/Raven_DC.jpg"},
    {"name":"Робин","image":"images/heroes_and_villains/Robin.jpg"},
    {"name":"Росомаха","image":"images/heroes_and_villains/images"},
    {"name":"Ртуть","image":"https://upload.wikimedia.org/wikipedia/uk/0/0e/Quicksilver_Marvel.jpg"},
    {"name":"Саблезубый","image":"https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/461233bb_b486_4fa1_ae9d_02aeb39130f5.jpeg"},
    {"name":"Серебряный Серфер","image":"images/heroes_and_villains/690"},
    {"name":"Синестро","image":"https://upload.wikimedia.org/wikipedia/ru/4/49/Sinestro-by-Ethan-Van-Sciver..jpeg"},
    {"name":"Сокол","image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBTZ7hV_tmSOWNX-RGSfwoesr5jEBnm_Fvhw&s"},
    {"name":"Соломон Гранди","image":"https://upload.wikimedia.org/wikipedia/ru/8/8a/Grundyfoe.png"},
    {"name":"Сорвиголова","image":"images/heroes_and_villains/daredevil-comics-67c5eff869c24.jpg"},
    {"name":"Стервятник","image":"images/heroes_and_villains/1596940405_stervyatnik-vulture.jpg"},
    {"name":"Супермен","image":"images/heroes_and_villains/spw20_p16-03.png"},
    {"name":"Существо","image":"images/heroes_and_villains/thing.jpg"},
    {"name":"Танос","image":"images/heroes_and_villains/marvel-marvel-thanos-annual-1-1131598176.jpg"},
    {"name":"Тор","image":"images/heroes_and_villains/83.1.jpg"},
    {"name":"Флэш","image":"images/heroes_and_villains/flash-6.png"},
    {"name":"Халк","image":"images/heroes_and_villains/how-strong-is-hulk-in-marvel-comics-v0-7bkz4920grfe1.jpeg"},
    {"name":"Харли Квинн","image":"https://miro.medium.com/1*ScYsBt0OePgkm_bugL9I_A.jpeg"},
    {"name":"Циклоп","image":"images/heroes_and_villains/2fc4e05a158d3a700ad7363bae720f17.jpg"},
    {"name":"Человек-паук","image":"images/heroes_and_villains/16def84ef90920c848e0e076d9b2df97.jpg"},
    {"name":"Человек-факел","image":"images/heroes_and_villains/human_torch_billy_tan54cv.jpg"},
    {"name":"Черная вдова","image":"images/heroes_and_villains/250"},
    {"name":"Черная Пантера","image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcjx2i-cme9VQw8u9e9fezlL-SUAUBMjNRqg&s"},
    {"name":"Черный Адам","image":"https://upload.wikimedia.org/wikipedia/ru/1/1e/Blackadam52.PNG"},
    {"name":"Чудо-женщина","image":"images/heroes_and_villains/large.file_723361.jpg.1a5fc2ff89b7ce0631d637a794e08ab3.jpg"},
    {"name":"Шазам","image":"images/heroes_and_villains/dc-comics-shazam-1-the-captain-dan-mora.png"},
    {"name":"Электро","image":"images/heroes_and_villains/1421869236_electro-in-1960s-spider-man.jpg"},
    {"name":"Ядовитый Плющ","image":"images/heroes_and_villains/4a61e92a9fa805e9121245ee867472a8.jpg"},
    {"name":"Ящер","image":"images/heroes_and_villains/ezgif-3-10e1ce19b6.jpg"}
];
